apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: 3tier-app
stringData:
  DB_PASSWORD: Ansar
  JWT_SECRET: devopsShackSuperSecretKey
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: 3tier-app
data:
  DB_HOST: mysql
  DB_USER: root
  DB_NAME: crud_app
  RESET_ADMIN_PASS: "true"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: 3tier-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: backend-app
        image: ansarshaik/3tierappback:latest
        ports:
        - containerPort: 5000
        env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: RESET_ADMIN_PASS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RESET_ADMIN_PASS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

